baseurl = "/"
languageCode = "en-us"
title = "Semi-Coherent Infoblag"
theme = "blackburn"
pygmentsstyle = "tango"

[params]
googleAnalytics = "UA-60679520-3"
subtitle = "Probably won't catch fire"

[taxonomies]
architecture = "architectures"
distribution = "distributions"
component = "components"
tag = "tags"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 1
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Git"
    pre = "<i class='fa fa-git fa-fw'></i>"
    weight = 2
    identifier = "git"
    url = "http://git.willhughes.name/"
  [[menu.main]]
    name = "Repo"
    pre = "<i class='fa fa-cube fa-fw'></i>"
    weight = 3
    identifier = "repo"
    url = "/repo/"
  [[menu.main]]
    name = "Search"
    pre = "<i class='fa fa-search fa-fw'></i>"
    weight = 3
    identifier = "search"
    url = "/search/"


[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "nzwillhughes"
  github = "insertjokehere"
