baseurl = "https://www.willhughes.name/"
languageCode = "en-us"
title = "Semi-Coherent Infoblag"
theme = "blackburn"

[taxonomies]
architecture = "architectures"
distribution = "distributions"
component = "components"

[indexes]
tag = "blog"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 1
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Git"
    pre = "<i class='fa fa-git fa-fw'></i>"
    weight = 2
    identifier = "git"
    url = "http://git.willhughes.name/"
  [[menu.main]]
    name = "Repo"
    pre = "<i class='fa fa-cube fa-fw'></i>"
    weight = 3
    identifier = "repo"
    url = "/repo/"


[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "nzwillhughes"
  github = "insertjokehere"
